### ISSUE TITLE
Documentation Effort

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/Treasury#155]
# Why?

Treasury's documentation could be considered relatively good at this point, however, since we use a concurrency system, it is more difficult to use. Therefore we need to provide very solid documentation if we have any hopes of gaining adoption in the community.

***

# Things to do

### Cover all the updates since 1.0.0
Basically update the wiki with all the changes that occurred afterwards (2.0.0 included).

- [x] All unlisted Wiki pages.
- [x] https://github.com/ArcanePlugins/Treasury/wiki/Permissions
- [x] https://github.com/ArcanePlugins/Treasury/wiki/messages.yml
- [x] https://github.com/ArcanePlugins/Treasury/wiki/settings.yml
- [x] https://github.com/ArcanePlugins/Treasury/wiki/Treasury-Placeholders

### Add 'Getting Started' page - short and concise version to get started with Treasury.

- [x] Page created
- [x] Created draft
- [x] Refined content

The average developer probably doesn't want to read all the details about the economy API, rather, just want to know how to do these simple operations:

* add maven repo
* get the economy provider from the service registry
* get/set balance, withdraw, deposit to player accounts
  * We will absolutely be showing CompletableFuture examples on this page. We should still touch on just the standard EconomySubscriber at the bottom of the page, but we must promote Futures over Subscribers for cleanliness and ease of use.
* Although we must heavily recommend against doing so, we should show how developers can run the CompletableFutures synchronously in the case that it is unfeasible for them to use Treasury due to poorly designed code that lacks concurrency.

Thank you to AlonsoAliaga for suggesting this.

## Javadocs

Javadocs must be improved as a whole. See #250.

**Comment by MrNemo64** [comment]
They're right

**Comment by lokka30** [comment]
> They're right

Absolutely. I'll work on this

**Comment by lokka30** [comment]
TODO: add constrictions to all methods, add documentation for using all methods with futures

**Comment by MrNemo64** [comment]
Since the release of Java 18, code in the javadoc is a feature. Would it be possible to use it?
https://youtu.be/m2cVOYuVs1U?t=102

**Comment by lokka30** [comment]
> Since the release of Java 18, code in the javadoc is a feature. Would it be possible to use it? https://youtu.be/m2cVOYuVs1U?t=102

Cool feature! I'm interested so long it doesn't cause any complications in the CI systems.

**Comment by lokka30** [comment]
Status: Began work. Updated OP.

**Comment by lokka30** [comment]
Status: To speed up the release of V2, I'd prefer to just have the quickstart pages be the only barrier before we can push out v2 and have eyes on whether or not people think they'll want to adopt it.

**Comment by lokka30** [comment]
Fully or mostly completed this quickstart page: https://github.com/ArcanePlugins/Treasury/wiki/Quickstart:-Economy-Consumer

**Comment by lokka30** [comment]
Written part of the Economy Provider quickstart guide.

Reformatted the sidebar of the Wiki.

Moved some of this issue's to-do list over to #280 since they aren't anywhere near as urgent as the quickstart guides.

**Comment by lokka30** [comment]
Wiki appears to be in a state suitable enough for launch.
