### ISSUE TITLE
Add treasury to the "Resource list" Wiki Page

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/Treasury#194]
### Discussed in https://github.com/lokka30/Treasury/discussions/141

<div type='discussions-op-text'>

<sup>Originally posted by **MrNemo64** February  6, 2022</sup>
A while ago I created [this](https://www.spigotmc.org/wiki/resources-list/) spigot wiki page. It is ment to be an index/list of all the apis and frameworks plugin developers have created, to make it easyer to check if something already existed without having to spend hours searching it.
I think we should add it to the page but since it's scope is going to keep on growing I really don't know how to post it</div>

**Comment by MrNemo64** [comment]
I think we could have each API of Treasury on its section. It's what I've done with the Uppercore framework

https://www.spigotmc.org/threads/uppercore-a-features-rich-core-for-plugins-development-1-15-2.445313/

**Comment by lokka30** [comment]
> I think we could have each API of Treasury on its section. It's what I've done with the Uppercore framework
> 
> https://www.spigotmc.org/threads/uppercore-a-features-rich-core-for-plugins-development-1-15-2.445313/

Which section(s), existing or not, shall we place Treasury's APIs? 🙂

**Comment by MrIvanPlays** [comment]
@MrNemo64 this has been on hold for 2 months now. Add it to wherever you feel like belongs.

**Comment by lokka30** [comment]
Issue is stale, feel free to re-open
