### ISSUE TITLE
Add nullability annotations on methods

### ISSUE THREAD

**Issue by MrIvanPlays** [ArcanePlugins/Treasury#221]
since v2 migrated from subscribers to futures, we forgot to add `@NotNull` annotations on the return values of methods changed.

**Comment by lokka30** [comment]
> Imo we should also consider https://github.com/osundblad/intellij-annotations-instrumenter-maven-plugin to ease the workload of adding nullity annotations. It's easy to forget manual null checks when annotating.

My personal preference is to do these manually.

**Comment by MrIvanPlays** [comment]
@lokka30 this library's about adding `Objects.requireNonNull` calls on fields annotated with `@NotNull`.

**Comment by lokka30** [comment]
> @lokka30 this library's about adding `Objects.requireNonNull` calls on fields annotated with `@NotNull`.

Thanks for clarifying – I'm happy to use it for that specific function. I'm being careful not to overstep with automation.
