### ISSUE TITLE
Nag about "not properly shutting down tasks" 

### ISSUE THREAD

**Issue by MrIvanPlays** [ArcanePlugins/Treasury#234]
```[16:37:00] [Server thread/ERROR]: Nag author: 'lokka30' of 'Treasury' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies```

Happens on Paper.
**Treasury v2 only**

Did some investigation, couldn't find any code that doesn't shut down tasks.

~~Bukkit sucks, prove me wrong~~

**Comment by MrIvanPlays** [comment]
This is some severe bullshit. Whilst yes I found the placeholder api hook tasks were not shutting down and i fixed it (commit not pushed yet), the nagging continues. Another weird problem is that I made it `stdout` all pending tasks. (Un)fortunately nothing was logged.

**Comment by MrIvanPlays** [comment]
Ye we need paper's assistance here. Can you make some1 from their team have a look at our code? If they can't find anything wrong with it then it is not our problem.

**Comment by lokka30** [comment]
Paper maintainers don't have much spare time, and neither me or them want to waste it, so I will need to do some testing first to try isolate where the issue is coming from.

**Comment by MrIvanPlays** [comment]
I've isolated the problem to be inside the PlaceholderAPI hook. Removing PlaceholderAPI from starting fixes the issue. I'll investigate further and probably fix the issue.

**Comment by MrIvanPlays** [comment]
@A248 you're the master of concurrency and stuff - if you can help here, do it. thx

**Comment by A248** [comment]
Alright, sure. May I take advantage of the commit you mentioned here?

> Whilst yes I found the placeholder api hook tasks were not shutting down and i fixed it (commit not pushed yet), the nagging continues

Maybe create a new branch to work on this bug. I'll PR to it.

**Comment by MrIvanPlays** [comment]
It is already pushed. Never mentioned it here

**Comment by MrIvanPlays** [comment]
@A248 any updates so far?

**Comment by A248** [comment]
No, I haven't started working on this yet. I likely won't have time for it until spring break (March 5). If you'd like to work on it before then, feel free.

**Comment by MrIvanPlays** [comment]
oddly enough I cannot reproduce this for 1.19.3 . I'm just gonna close this issue.
