### ISSUE TITLE
`EconomyTransaction`: Rename some variables, getters and setters

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/Treasury#254]
Some variables (along with their respective getters and setters) should be renamed:

- `transactionAmount` -> `amount`
- `currencyID` -> `currencyId`
- `economyTransactionType` -> `type`

**Comment by MrIvanPlays** [comment]
Why?

**Comment by Jikoo** [comment]
Not opposed to these, but is it a large enough concern to bother? I do prefer Google's style of lowercasing subsequent letters in abbreviations. Is that specifically an inconsistency across the project?

**Comment by MrIvanPlays** [comment]
What you're doing here is creating an elephant from a fly.

**Comment by MrIvanPlays** [comment]
fixed in https://github.com/ArcanePlugins/Treasury/commit/ed5847d6be5a629ddf8d3ec1afb73cef4996fec7 and https://github.com/ArcanePlugins/Treasury/commit/57e8a3eddffe95b4ac245459d8f1c6f74a991142
