### ISSUE TITLE
`Currency`: Should we map display names against locales?

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/Treasury#255]
Currently, display names are not translatable per-locale in [`Currency`](https://github.com/ArcanePlugins/Treasury/blob/dev/2.0.0/api/src/main/java/me/lokka30/treasury/api/economy/currency/Currency.java), which does not conform with the other translatable features (being the decimal char, formatting, and parsing).

Should the display names (singular and plural) be mapped by locale, just like the decimal char is?

**Comment by MrIvanPlays** [comment]
sure why not

**Comment by Jikoo** [comment]
I'm not opposed to it. This being MC, currencies are much more likely to be things like "gold" or "coins" and have translations, unlike many real-world currencies.

**Comment by MrIvanPlays** [comment]
fixed in https://github.com/ArcanePlugins/Treasury/commit/ed5847d6be5a629ddf8d3ec1afb73cef4996fec7 and https://github.com/ArcanePlugins/Treasury/commit/57e8a3eddffe95b4ac245459d8f1c6f74a991142
