### ISSUE TITLE
`Account`: Rename `setPermission`, `hasPermission` to use a plural

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/Treasury#257]
In [`Account`](), I will rename `setPermission` and `hasPermission` to `setPermissions` and `hasPermissions` respectively. This is because they accept a *list* of permissions, not just a single permission. Not only does this raise the level of consistency in the API, it's better grammatical practice.

**Comment by MrIvanPlays** [comment]
making an elephant from a fly...

**Comment by lokka30** [comment]
> making an elephant from a fly...

so, yes?

**Comment by MrIvanPlays** [comment]
fixed in https://github.com/ArcanePlugins/Treasury/commit/ed5847d6be5a629ddf8d3ec1afb73cef4996fec7 and https://github.com/ArcanePlugins/Treasury/commit/57e8a3eddffe95b4ac245459d8f1c6f74a991142
