### ISSUE TITLE
`Account`: add another `setPermissions` method which accepts a `Map<perm, state>`

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/Treasury#259]
to complement `retrievePermissions`we may want to have a `setPermissions` method which works with a permission-state map.

**Comment by MrIvanPlays** [comment]
it should also accept an account

**Comment by MrIvanPlays** [comment]
fixed in https://github.com/ArcanePlugins/Treasury/commit/ed5847d6be5a629ddf8d3ec1afb73cef4996fec7 and https://github.com/ArcanePlugins/Treasury/commit/57e8a3eddffe95b4ac245459d8f1c6f74a991142
