### ISSUE TITLE
Change currency identifier to NamespacedKey

### ISSUE THREAD

**Issue by MrIvanPlays** [ArcanePlugins/Treasury#265]
thoughts

**Comment by lokka30** [comment]
I don't think so:

Currencies are referenced by name and there shouldn't be multiple currencies registered with the same name (even if they have a different namespace, in the case of this particular suggestion).

The reasons that Non-Player accounts were given namespacedkey identifiers are different to this scenario.

Let me know if you'd like an elaboration 🙂

**Comment by MrIvanPlays** [comment]
idk it just doesn't feel right to be a string identifier. no particular reason, i don't really care whether we leave it like that or change it, i'd like to hear some opinions.

@Jikoo thoughts?

**Comment by lokka30** [comment]
For instance if I have a balance command like this: `/eco set [player] [amount] [currency]`,
I wouldn't want to write something like `/eco set MrIvanPlays 1500.50 theneweconomy:dollar`.

**Comment by Jikoo** [comment]
I guess it wouldn't hurt, but it does seem like a bit of a pain for a relatively niche case. I imagine people would only have currency name conflicts while they're migrating economies.

**Comment by lokka30** [comment]
I agree that currency name conflicts can happen during migration, though I don't see any other use case for this, and I do think it would hurt to implement it. Still open to discuss it of course, but I'm currently on the negative end :smiley:

**Comment by MrIvanPlays** [comment]
ok we're leaving it like that
