### ISSUE TITLE
Publish to Hangar

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/Treasury#275]
Hangar allows us to release multiple platform JARs instead of telling people to go download it from a CI. Totally awesome.

https://hangar.papermc.io/ArcanePlugins/treasury

Not sure if Hangar is showing it yet - may only be accessible to some

@Jikoo I'd like to add you as a maintainer on Hangar if you've got an account

**Comment by MrIvanPlays** [comment]
It doesn't show it because you haven't published a jar yet.

**Comment by lokka30** [comment]
That's intentional. I should have specified whether you guys can see it or not - I don't want the public to see the unwritten page yet. 👍

**Comment by Jikoo** [comment]
I've created an account, jikoo there as well. Does Hangar support other project channels? I was under the impression that their channels were more alpha/beta/release for Paper/Waterfall/Velocity. Either way, definitely a good place to support.

**Comment by lokka30** [comment]
Thanks Jikoo, sent an invitation :)

Status: need to write the page and the page will be active once we upload v2 to it.

**Comment by MrIvanPlays** [comment]
Page active now. Treasury's being released on Hangar too!
