### ISSUE TITLE
New module: `api-utilities`

### ISSUE THREAD

**Issue by MrIvanPlays** [ArcanePlugins/Treasury#63]
This module would feature stuff such as gson serializers for `Account`, `NonPlayerAccount`, `PlayerAccount`, `Transaction` and `Currency`.

I don't think such stuff shall be part of the general API as not every economy provider will choose to support gson for storage or would like any of these enhancements.

Another names for this module I can think of is `api-enhancements` or `api-extensions` or `api-qol-utils` if you do not agree with the name I suggest.

This is a low prio issue, not really important, I'm opening this for discussion.

**Comment by MrNemo64** [comment]
I like the idea, it also kinda fits #12, an optional extension of the api

**Comment by MrIvanPlays** [comment]
> I like the idea, it also kinda fits #12, an optional extension of the api

as lokka30 mentioned, #12 will be separate project aside treasury. fairly sure it won't be a module of treasury or planned as such.

**Comment by MrNemo64** [comment]
> > I like the idea, it also kinda fits #12, an optional extension of the api
> 
> as lokka30 mentioned, #12 will be separate project aside treasury. fairly sure it won't be a module of treasury or planned as such.

RIght, forgot about that

**Comment by lokka30** [comment]
I like the idea of this issue
I agree with using the module name `api-utilities`.
An example package name would be `me.lokka30.treasury.api-utilities.economy`.

**Comment by lokka30** [comment]
I believe we should create the Maven module now, but putting any code in it is not required for release.

**Comment by MrIvanPlays** [comment]
this is not going to be done in pre release stage as treasury's currently not stable enough. stuff is changing in matter of days.

**Comment by MrIvanPlays** [comment]
I'm gonna revisit this and imo this is not really needed. I can't see a use-case for it, except for economy plugins implementing this as their way of storage.

**Comment by lokka30** [comment]
I haven't come up with any ideas for this module.

**Comment by MrIvanPlays** [comment]
Closing due to low demand for such module. Also given the edge-case nature of it, I don't think this is needed (for now).
